# 配置内置Tomcat端口
server:
  port: 6066
# 配置rabbitMQ基本信息
spring:
  rabbitmq:
    port: 5672
    # 修改为rabbitMQ集群端口
    host: 192.168.182.134,192.168.182.135
    #host: 192.168.182.131
    username: root
    password: root
    virtual-host: /
  application:
    name: rabbitmq-springboot-provider

