# 配置内置Tomcat端口
server:
  port: 6068
# 配置rabbitMQ基本信息
spring:
  rabbitmq:
    port: 5672
    #  rabbitMQ集群端口
    host: 192.168.182.135,192.168.182.134
    #host: 192.168.182.131
    username: root
    password: root
    virtual-host: /
